language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - 'pypy'
  - 'pypy3'
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -e .[test]
script:
  - flake8 *.py
  - python run_tests.py
after_success:
  - pip install -q coverage==3.7.1 coveralls pytest-cov
  - py.test run_tests.py --cov flake8_pep3101 --cov-report term-missing
  - coveralls
