language: python
python:
  - '2.7'
  - '3.6'
  - '3.7'
  - 'pypy'
  - 'pypy3'
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install pip-tools
  - pip-sync requirements.txt
script:
  - flake8 *.py
  - pytest run_tests.py
after_success:
  - pip install -q coveralls
  - py.test run_tests.py --cov flake8_pep3101 --cov-report term-missing
  - coveralls
